#!/bin/bash
set -eu

SECRETS=("FIREBASE_SERVICE_ACCOUNT" "FIREBASE_CONFIG_READ" "LINE_TOKENS_N_TARGETS" "OPENAI_KEY_OML" "X_CONSUMER_KEY" "X_CONSUMER_SECRET" "X_ACCESS_TOKEN" "X_ACCESS_TOKEN_SECRET")
